version: '3.9'
services:
  # ! COMMENT THIS SERVICE BECAUSE RUN SERVER ON LOCAL COMPUTER, NOT ON DOCKER SIDE
  # ! BECAUSE LAGGING
  # backend:
  #   build: . # dot mean create a build from Dockerfile
  #   ports:
  #     - 3001:3001 # port in local computer | port in local container
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - db # make backend services related to db services. db services will run first

  db:
    # image: mysql
    # platform: linux/x86_64
    platform: linux/arm64/v8
    image: arm64v8/mysql:oracle
    restart: always
    environment:
      MYSQL_DATABASE: nest_auth_template
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3306:3306
