AWSTemplateFormatVersion: '2010-09-09'

Resources:
  SongsDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      DBInstanceIdentifier: nest-auth-template
      PubliclyAccessible: true
      StorageType: gp2
      MasterUsername: admin
      MasterUserPassword: password
      Engine: mysql
      EngineVersion: 8.0.28
